# Generated by Django 5.2.15 on 2026-06-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('document', ''), _negated=True), fields=('document',), name='customer_unique_document', violation_error_message='Ya existe un cliente con este documento.'),
        ),
    ]
